/* File: interface_fmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Fri Jul  7 07:14:24 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <setjmp.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *interface_f_error;
static PyObject *interface_f_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef float(*cb_pres_in_riemann_cgf__user__routines_typedef)(double *);
typedef float(*cb_real_gamma_in_riemann_cgf__user__routines_typedef)(double *);
typedef float(*cb_speed_in_states__user__routines_typedef)(double *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define PRINTPYOBJERR(obj)\
  fprintf(stderr,"interface_f.error is related to ");\
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");

#define GETSCALARFROMPYTUPLE(tuple,index,var,ctype,mess) {\
    if ((capi_tmp = PyTuple_GetItem((tuple),(index)))==NULL) goto capi_fail;\
    if (!(ctype ## _from_pyobj((var),capi_tmp,mess)))\
      goto capi_fail;\
  }

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define SWAP(a,b,t) {\
  t *c;\
  c = a;\
  a = b;\
  b = c;}

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(interface_f_error,errstring);\
    /*goto capi_fail;*/\
  } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = interface_f_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
  PyObject *tmp = NULL;
  PyObject *tmp_fun = NULL;
  int tot,opt,ext,siz,i,di=0;
  CFUNCSMESS("create_cb_arglist\n");
  tot=opt=ext=siz=0;
  /* Get the total number of arguments */
  if (PyFunction_Check(fun))
    tmp_fun = fun;
  else {
    di = 1;
    if (PyObject_HasAttrString(fun,"im_func")) {
      tmp_fun = PyObject_GetAttrString(fun,"im_func");
    }
    else if (PyObject_HasAttrString(fun,"__call__")) {
      tmp = PyObject_GetAttrString(fun,"__call__");
      if (PyObject_HasAttrString(tmp,"im_func"))
        tmp_fun = PyObject_GetAttrString(tmp,"im_func");
      else {
        tmp_fun = fun; /* built-in function */
        tot = maxnofargs;
        if (xa != NULL)
          tot += PyTuple_Size((PyObject *)xa);
      }
      Py_XDECREF(tmp);
    }
    else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        tot += PyTuple_Size((PyObject *)xa);
      tmp_fun = fun;
    }
    else if (F2PyCapsule_Check(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
      if(ext>0) {
        fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
        goto capi_fail;
      }
      tmp_fun = fun;
    }
  }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
  if (PyObject_HasAttrString(tmp_fun,"__code__")) {
    if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
  if (PyObject_HasAttrString(tmp_fun,"func_code")) {
    if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
      tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
    Py_XDECREF(tmp);
  }
  /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
  if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
    if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
  if (PyObject_HasAttrString(tmp_fun,"func_defaults")) {
    if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
      opt = PyTuple_Size(tmp);
    Py_XDECREF(tmp);
  }
  /* Get the number of extra arguments */
  if (xa != NULL)
    ext = PyTuple_Size((PyObject *)xa);
  /* Calculate the size of call-backs argument list */
  siz = MIN(maxnofargs+ext,tot);
  *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
  fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
  if (siz<tot-opt) {
    fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
    goto capi_fail;
  }
  /* Initialize argument list */
  *args = (PyTupleObject *)PyTuple_New(siz);
  for (i=0;i<*nofargs;i++) {
    Py_INCREF(Py_None);
    PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
  }
  if (xa != NULL)
    for (i=(*nofargs);i<siz;i++) {
      tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
      Py_INCREF(tmp);
      PyTuple_SET_ITEM(*args,i,tmp);
    }
  CFUNCSMESS("create_cb_arglist-end\n");
  return 1;
capi_fail:
  if ((PyErr_Occurred())==NULL)
    PyErr_SetString(interface_f_error,errmess);
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = interface_f_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(states,STATES)(int*,int*,int*,int*,double*,double*,int*,cb_speed_in_states__user__routines_typedef,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*);
extern void F_FUNC_US(riemann_cgf,RIEMANN_CGF)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,cb_real_gamma_in_riemann_cgf__user__routines_typedef,cb_pres_in_riemann_cgf__user__routines_typedef,double*,double*,double*);
extern void F_FUNC_US(riemann_HLLC,RIEMANN_HLLC)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*);
extern void F_FUNC(consFlux,CONSFLUX)(int*,double*,int*,int*,int*,int*,int*,double*,double*);
extern void F_FUNC_US(artificial_viscosity,ARTIFICIAL_VISCOSITY)(int*,int*,int*,double*,double*,double*,double*,double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/********************* cb_speed_in_states__user__routines *********************/
PyObject *cb_speed_in_states__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_speed_in_states__user__routines_args_capi = NULL;
int cb_speed_in_states__user__routines_nofargs = 0;
jmp_buf cb_speed_in_states__user__routines_jmpbuf;
/*typedef float(*cb_speed_in_states__user__routines_typedef)(double *);*/
static float cb_speed_in_states__user__routines (double *new_bn) {
  PyTupleObject *capi_arglist = cb_speed_in_states__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  float return_value;
  npy_intp new_bn_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_speed_in_states__user__routines (maxnofargs=1(-0))\n");
  CFUNCSMESSPY("cb:cb_speed_in_states__user__routines_capi=",cb_speed_in_states__user__routines_capi);
  if (cb_speed_in_states__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_speed_in_states__user__routines_capi = PyObject_GetAttrString(interface_f_module,"speed");
  }
  if (cb_speed_in_states__user__routines_capi==NULL) {
    PyErr_SetString(interface_f_error,"cb: Callback speed not defined (as an argument or module interface_f attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_speed_in_states__user__routines_capi)) {
  cb_speed_in_states__user__routines_typedef cb_speed_in_states__user__routines_cptr;
  cb_speed_in_states__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_speed_in_states__user__routines_capi);
  return_value=(*cb_speed_in_states__user__routines_cptr)(new_bn);
    return return_value;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(interface_f_module,"speed_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(interface_f_error,"Failed to convert interface_f.speed_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(interface_f_error,"Callback speed argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  new_bn_Dims[0]=2;
/*pyobjfrom*/
  if (cb_speed_in_states__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,new_bn_Dims,NPY_DOUBLE,NULL,(char*)new_bn,0,NPY_ARRAY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function speed.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_speed_in_states__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,&return_value,float,"float_from_pyobj failed in converting return_value of call-back function cb_speed_in_states__user__routines to C float\n");
  CFUNCSMESS("cb:cb_speed_in_states__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_speed_in_states__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_speed_in_states__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
  return return_value;
}
/***************** end of cb_speed_in_states__user__routines *****************/


/**************** cb_real_gamma_in_riemann_cgf__user__routines ****************/
PyObject *cb_real_gamma_in_riemann_cgf__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_real_gamma_in_riemann_cgf__user__routines_args_capi = NULL;
int cb_real_gamma_in_riemann_cgf__user__routines_nofargs = 0;
jmp_buf cb_real_gamma_in_riemann_cgf__user__routines_jmpbuf;
/*typedef float(*cb_real_gamma_in_riemann_cgf__user__routines_typedef)(double *);*/
static float cb_real_gamma_in_riemann_cgf__user__routines (double *temp) {
  PyTupleObject *capi_arglist = cb_real_gamma_in_riemann_cgf__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  float return_value;
  npy_intp temp_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_real_gamma_in_riemann_cgf__user__routines (maxnofargs=1(-0))\n");
  CFUNCSMESSPY("cb:cb_real_gamma_in_riemann_cgf__user__routines_capi=",cb_real_gamma_in_riemann_cgf__user__routines_capi);
  if (cb_real_gamma_in_riemann_cgf__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_real_gamma_in_riemann_cgf__user__routines_capi = PyObject_GetAttrString(interface_f_module,"real_gamma");
  }
  if (cb_real_gamma_in_riemann_cgf__user__routines_capi==NULL) {
    PyErr_SetString(interface_f_error,"cb: Callback real_gamma not defined (as an argument or module interface_f attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_real_gamma_in_riemann_cgf__user__routines_capi)) {
  cb_real_gamma_in_riemann_cgf__user__routines_typedef cb_real_gamma_in_riemann_cgf__user__routines_cptr;
  cb_real_gamma_in_riemann_cgf__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_real_gamma_in_riemann_cgf__user__routines_capi);
  return_value=(*cb_real_gamma_in_riemann_cgf__user__routines_cptr)(temp);
    return return_value;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(interface_f_module,"real_gamma_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(interface_f_error,"Failed to convert interface_f.real_gamma_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(interface_f_error,"Callback real_gamma argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  temp_Dims[0]=2;
/*pyobjfrom*/
  if (cb_real_gamma_in_riemann_cgf__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,temp_Dims,NPY_DOUBLE,NULL,(char*)temp,0,NPY_ARRAY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function real_gamma.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_real_gamma_in_riemann_cgf__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,&return_value,float,"float_from_pyobj failed in converting return_value of call-back function cb_real_gamma_in_riemann_cgf__user__routines to C float\n");
  CFUNCSMESS("cb:cb_real_gamma_in_riemann_cgf__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_real_gamma_in_riemann_cgf__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_real_gamma_in_riemann_cgf__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
  return return_value;
}
/************ end of cb_real_gamma_in_riemann_cgf__user__routines ************/


/******************* cb_pres_in_riemann_cgf__user__routines *******************/
PyObject *cb_pres_in_riemann_cgf__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_pres_in_riemann_cgf__user__routines_args_capi = NULL;
int cb_pres_in_riemann_cgf__user__routines_nofargs = 0;
jmp_buf cb_pres_in_riemann_cgf__user__routines_jmpbuf;
/*typedef float(*cb_pres_in_riemann_cgf__user__routines_typedef)(double *);*/
static float cb_pres_in_riemann_cgf__user__routines (double *temp) {
  PyTupleObject *capi_arglist = cb_pres_in_riemann_cgf__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  float return_value;
  npy_intp temp_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_pres_in_riemann_cgf__user__routines (maxnofargs=1(-0))\n");
  CFUNCSMESSPY("cb:cb_pres_in_riemann_cgf__user__routines_capi=",cb_pres_in_riemann_cgf__user__routines_capi);
  if (cb_pres_in_riemann_cgf__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_pres_in_riemann_cgf__user__routines_capi = PyObject_GetAttrString(interface_f_module,"pres");
  }
  if (cb_pres_in_riemann_cgf__user__routines_capi==NULL) {
    PyErr_SetString(interface_f_error,"cb: Callback pres not defined (as an argument or module interface_f attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_pres_in_riemann_cgf__user__routines_capi)) {
  cb_pres_in_riemann_cgf__user__routines_typedef cb_pres_in_riemann_cgf__user__routines_cptr;
  cb_pres_in_riemann_cgf__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_pres_in_riemann_cgf__user__routines_capi);
  return_value=(*cb_pres_in_riemann_cgf__user__routines_cptr)(temp);
    return return_value;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(interface_f_module,"pres_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(interface_f_error,"Failed to convert interface_f.pres_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(interface_f_error,"Callback pres argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  temp_Dims[0]=2;
/*pyobjfrom*/
  if (cb_pres_in_riemann_cgf__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,temp_Dims,NPY_DOUBLE,NULL,(char*)temp,0,NPY_ARRAY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function pres.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_pres_in_riemann_cgf__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,&return_value,float,"float_from_pyobj failed in converting return_value of call-back function cb_pres_in_riemann_cgf__user__routines to C float\n");
  CFUNCSMESS("cb:cb_pres_in_riemann_cgf__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_pres_in_riemann_cgf__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_pres_in_riemann_cgf__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
  return return_value;
}
/*************** end of cb_pres_in_riemann_cgf__user__routines ***************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** states ***********************************/
static char doc_f2py_rout_interface_f_states[] = "\
q_l,q_r = states(idir,qx,qy,ng,dx,dt,nvar,speed,r,u,v,p,ldelta_r,ldelta_u,ldelta_v,ldelta_p,[speed_extra_args])\n\nWrapper for ``states``.\
\n\nParameters\n----------\n"
"idir : input int\n"
"qx : input int\n"
"qy : input int\n"
"ng : input int\n"
"dx : input float\n"
"dt : input float\n"
"nvar : input int\n"
"speed : call-back function\n"
"r : input rank-2 array('d') with bounds (qx,qy)\n"
"u : input rank-2 array('d') with bounds (qx,qy)\n"
"v : input rank-2 array('d') with bounds (qx,qy)\n"
"p : input rank-2 array('d') with bounds (qx,qy)\n"
"ldelta_r : input rank-2 array('d') with bounds (qx,qy)\n"
"ldelta_u : input rank-2 array('d') with bounds (qx,qy)\n"
"ldelta_v : input rank-2 array('d') with bounds (qx,qy)\n"
"ldelta_p : input rank-2 array('d') with bounds (qx,qy)\n"
"\nOther Parameters\n----------------\n"
"speed_extra_args : input tuple, optional\n    Default: ()\n"
"\nReturns\n-------\n"
"q_l : rank-3 array('d') with bounds (qx,qy,nvar)\n"
"q_r : rank-3 array('d') with bounds (qx,qy,nvar)\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"  def speed(new_bn): return sound\n\
  Required arguments:\n"
"    new_bn : input rank-1 array('d') with bounds (2)\n"
"  Return objects:\n"
"    sound : float";
/* extern void F_FUNC(states,STATES)(int*,int*,int*,int*,double*,double*,int*,cb_speed_in_states__user__routines_typedef,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_interface_f_states(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,double*,double*,int*,cb_speed_in_states__user__routines_typedef,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int idir = 0;
  PyObject *idir_capi = Py_None;
  int qx = 0;
  PyObject *qx_capi = Py_None;
  int qy = 0;
  PyObject *qy_capi = Py_None;
  int ng = 0;
  PyObject *ng_capi = Py_None;
  double dx = 0;
  PyObject *dx_capi = Py_None;
  double dt = 0;
  PyObject *dt_capi = Py_None;
  int nvar = 0;
  PyObject *nvar_capi = Py_None;
  PyObject *speed_capi = Py_None;
  PyTupleObject *speed_xa_capi = NULL;
  PyTupleObject *speed_args_capi = NULL;
  int speed_nofargs_capi = 0;
  cb_speed_in_states__user__routines_typedef speed_cptr;
  double *r = NULL;
  npy_intp r_Dims[2] = {-1, -1};
  const int r_Rank = 2;
  PyArrayObject *capi_r_tmp = NULL;
  int capi_r_intent = 0;
  PyObject *r_capi = Py_None;
  double *u = NULL;
  npy_intp u_Dims[2] = {-1, -1};
  const int u_Rank = 2;
  PyArrayObject *capi_u_tmp = NULL;
  int capi_u_intent = 0;
  PyObject *u_capi = Py_None;
  double *v = NULL;
  npy_intp v_Dims[2] = {-1, -1};
  const int v_Rank = 2;
  PyArrayObject *capi_v_tmp = NULL;
  int capi_v_intent = 0;
  PyObject *v_capi = Py_None;
  double *p = NULL;
  npy_intp p_Dims[2] = {-1, -1};
  const int p_Rank = 2;
  PyArrayObject *capi_p_tmp = NULL;
  int capi_p_intent = 0;
  PyObject *p_capi = Py_None;
  double *ldelta_r = NULL;
  npy_intp ldelta_r_Dims[2] = {-1, -1};
  const int ldelta_r_Rank = 2;
  PyArrayObject *capi_ldelta_r_tmp = NULL;
  int capi_ldelta_r_intent = 0;
  PyObject *ldelta_r_capi = Py_None;
  double *ldelta_u = NULL;
  npy_intp ldelta_u_Dims[2] = {-1, -1};
  const int ldelta_u_Rank = 2;
  PyArrayObject *capi_ldelta_u_tmp = NULL;
  int capi_ldelta_u_intent = 0;
  PyObject *ldelta_u_capi = Py_None;
  double *ldelta_v = NULL;
  npy_intp ldelta_v_Dims[2] = {-1, -1};
  const int ldelta_v_Rank = 2;
  PyArrayObject *capi_ldelta_v_tmp = NULL;
  int capi_ldelta_v_intent = 0;
  PyObject *ldelta_v_capi = Py_None;
  double *ldelta_p = NULL;
  npy_intp ldelta_p_Dims[2] = {-1, -1};
  const int ldelta_p_Rank = 2;
  PyArrayObject *capi_ldelta_p_tmp = NULL;
  int capi_ldelta_p_intent = 0;
  PyObject *ldelta_p_capi = Py_None;
  double *q_l = NULL;
  npy_intp q_l_Dims[3] = {-1, -1, -1};
  const int q_l_Rank = 3;
  PyArrayObject *capi_q_l_tmp = NULL;
  int capi_q_l_intent = 0;
  double *q_r = NULL;
  npy_intp q_r_Dims[3] = {-1, -1, -1};
  const int q_r_Rank = 3;
  PyArrayObject *capi_q_r_tmp = NULL;
  int capi_q_r_intent = 0;
  static char *capi_kwlist[] = {"idir","qx","qy","ng","dx","dt","nvar","speed","r","u","v","p","ldelta_r","ldelta_u","ldelta_v","ldelta_p","speed_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOO|O!:interface_f.states",\
    capi_kwlist,&idir_capi,&qx_capi,&qy_capi,&ng_capi,&dx_capi,&dt_capi,&nvar_capi,&speed_capi,&r_capi,&u_capi,&v_capi,&p_capi,&ldelta_r_capi,&ldelta_u_capi,&ldelta_v_capi,&ldelta_p_capi,&PyTuple_Type,&speed_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable speed */
if(F2PyCapsule_Check(speed_capi)) {
  speed_cptr = F2PyCapsule_AsVoidPtr(speed_capi);
} else {
  speed_cptr = cb_speed_in_states__user__routines;
}

  speed_nofargs_capi = cb_speed_in_states__user__routines_nofargs;
  if (create_cb_arglist(speed_capi,speed_xa_capi,1,0,&cb_speed_in_states__user__routines_nofargs,&speed_args_capi,"failed in processing argument list for call-back speed.")) {
    jmp_buf speed_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `speed`.\n");
    SWAP(speed_capi,cb_speed_in_states__user__routines_capi,PyObject);
    SWAP(speed_args_capi,cb_speed_in_states__user__routines_args_capi,PyTupleObject);
    memcpy(&speed_jmpbuf,&cb_speed_in_states__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable idir */
    f2py_success = int_from_pyobj(&idir,idir_capi,"interface_f.states() 1st argument (idir) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ng */
    f2py_success = int_from_pyobj(&ng,ng_capi,"interface_f.states() 4th argument (ng) can't be converted to int");
  if (f2py_success) {
  /* Processing variable dx */
    f2py_success = double_from_pyobj(&dx,dx_capi,"interface_f.states() 5th argument (dx) can't be converted to double");
  if (f2py_success) {
  /* Processing variable qx */
    f2py_success = int_from_pyobj(&qx,qx_capi,"interface_f.states() 2nd argument (qx) can't be converted to int");
  if (f2py_success) {
  /* Processing variable dt */
    f2py_success = double_from_pyobj(&dt,dt_capi,"interface_f.states() 6th argument (dt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nvar */
    f2py_success = int_from_pyobj(&nvar,nvar_capi,"interface_f.states() 7th argument (nvar) can't be converted to int");
  if (f2py_success) {
  /* Processing variable qy */
    f2py_success = int_from_pyobj(&qy,qy_capi,"interface_f.states() 3rd argument (qy) can't be converted to int");
  if (f2py_success) {
  /* Processing variable q_l */
  q_l_Dims[0]=qx,q_l_Dims[1]=qy,q_l_Dims[2]=nvar;
  capi_q_l_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_q_l_tmp = array_from_pyobj(NPY_DOUBLE,q_l_Dims,q_l_Rank,capi_q_l_intent,Py_None);
  if (capi_q_l_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting hidden `q_l' of interface_f.states to C/Fortran array" );
  } else {
    q_l = (double *)(PyArray_DATA(capi_q_l_tmp));

  /* Processing variable q_r */
  q_r_Dims[0]=qx,q_r_Dims[1]=qy,q_r_Dims[2]=nvar;
  capi_q_r_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_q_r_tmp = array_from_pyobj(NPY_DOUBLE,q_r_Dims,q_r_Rank,capi_q_r_intent,Py_None);
  if (capi_q_r_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting hidden `q_r' of interface_f.states to C/Fortran array" );
  } else {
    q_r = (double *)(PyArray_DATA(capi_q_r_tmp));

  /* Processing variable p */
  p_Dims[0]=qx,p_Dims[1]=qy;
  capi_p_intent |= F2PY_INTENT_IN;
  capi_p_tmp = array_from_pyobj(NPY_DOUBLE,p_Dims,p_Rank,capi_p_intent,p_capi);
  if (capi_p_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 12nd argument `p' of interface_f.states to C/Fortran array" );
  } else {
    p = (double *)(PyArray_DATA(capi_p_tmp));

  /* Processing variable ldelta_v */
  ldelta_v_Dims[0]=qx,ldelta_v_Dims[1]=qy;
  capi_ldelta_v_intent |= F2PY_INTENT_IN;
  capi_ldelta_v_tmp = array_from_pyobj(NPY_DOUBLE,ldelta_v_Dims,ldelta_v_Rank,capi_ldelta_v_intent,ldelta_v_capi);
  if (capi_ldelta_v_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 15th argument `ldelta_v' of interface_f.states to C/Fortran array" );
  } else {
    ldelta_v = (double *)(PyArray_DATA(capi_ldelta_v_tmp));

  /* Processing variable ldelta_u */
  ldelta_u_Dims[0]=qx,ldelta_u_Dims[1]=qy;
  capi_ldelta_u_intent |= F2PY_INTENT_IN;
  capi_ldelta_u_tmp = array_from_pyobj(NPY_DOUBLE,ldelta_u_Dims,ldelta_u_Rank,capi_ldelta_u_intent,ldelta_u_capi);
  if (capi_ldelta_u_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 14th argument `ldelta_u' of interface_f.states to C/Fortran array" );
  } else {
    ldelta_u = (double *)(PyArray_DATA(capi_ldelta_u_tmp));

  /* Processing variable ldelta_r */
  ldelta_r_Dims[0]=qx,ldelta_r_Dims[1]=qy;
  capi_ldelta_r_intent |= F2PY_INTENT_IN;
  capi_ldelta_r_tmp = array_from_pyobj(NPY_DOUBLE,ldelta_r_Dims,ldelta_r_Rank,capi_ldelta_r_intent,ldelta_r_capi);
  if (capi_ldelta_r_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 13rd argument `ldelta_r' of interface_f.states to C/Fortran array" );
  } else {
    ldelta_r = (double *)(PyArray_DATA(capi_ldelta_r_tmp));

  /* Processing variable ldelta_p */
  ldelta_p_Dims[0]=qx,ldelta_p_Dims[1]=qy;
  capi_ldelta_p_intent |= F2PY_INTENT_IN;
  capi_ldelta_p_tmp = array_from_pyobj(NPY_DOUBLE,ldelta_p_Dims,ldelta_p_Rank,capi_ldelta_p_intent,ldelta_p_capi);
  if (capi_ldelta_p_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 16th argument `ldelta_p' of interface_f.states to C/Fortran array" );
  } else {
    ldelta_p = (double *)(PyArray_DATA(capi_ldelta_p_tmp));

  /* Processing variable r */
  r_Dims[0]=qx,r_Dims[1]=qy;
  capi_r_intent |= F2PY_INTENT_IN;
  capi_r_tmp = array_from_pyobj(NPY_DOUBLE,r_Dims,r_Rank,capi_r_intent,r_capi);
  if (capi_r_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 9th argument `r' of interface_f.states to C/Fortran array" );
  } else {
    r = (double *)(PyArray_DATA(capi_r_tmp));

  /* Processing variable u */
  u_Dims[0]=qx,u_Dims[1]=qy;
  capi_u_intent |= F2PY_INTENT_IN;
  capi_u_tmp = array_from_pyobj(NPY_DOUBLE,u_Dims,u_Rank,capi_u_intent,u_capi);
  if (capi_u_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 10th argument `u' of interface_f.states to C/Fortran array" );
  } else {
    u = (double *)(PyArray_DATA(capi_u_tmp));

  /* Processing variable v */
  v_Dims[0]=qx,v_Dims[1]=qy;
  capi_v_intent |= F2PY_INTENT_IN;
  capi_v_tmp = array_from_pyobj(NPY_DOUBLE,v_Dims,v_Rank,capi_v_intent,v_capi);
  if (capi_v_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 11st argument `v' of interface_f.states to C/Fortran array" );
  } else {
    v = (double *)(PyArray_DATA(capi_v_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_speed_in_states__user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(&idir,&qx,&qy,&ng,&dx,&dt,&nvar,speed_cptr,r,u,v,p,ldelta_r,ldelta_u,ldelta_v,ldelta_p,q_l,q_r);
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_q_l_tmp,capi_q_r_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_v_tmp!=v_capi) {
    Py_XDECREF(capi_v_tmp); }
  }  /*if (capi_v_tmp == NULL) ... else of v*/
  /* End of cleaning variable v */
  if((PyObject *)capi_u_tmp!=u_capi) {
    Py_XDECREF(capi_u_tmp); }
  }  /*if (capi_u_tmp == NULL) ... else of u*/
  /* End of cleaning variable u */
  if((PyObject *)capi_r_tmp!=r_capi) {
    Py_XDECREF(capi_r_tmp); }
  }  /*if (capi_r_tmp == NULL) ... else of r*/
  /* End of cleaning variable r */
  if((PyObject *)capi_ldelta_p_tmp!=ldelta_p_capi) {
    Py_XDECREF(capi_ldelta_p_tmp); }
  }  /*if (capi_ldelta_p_tmp == NULL) ... else of ldelta_p*/
  /* End of cleaning variable ldelta_p */
  if((PyObject *)capi_ldelta_r_tmp!=ldelta_r_capi) {
    Py_XDECREF(capi_ldelta_r_tmp); }
  }  /*if (capi_ldelta_r_tmp == NULL) ... else of ldelta_r*/
  /* End of cleaning variable ldelta_r */
  if((PyObject *)capi_ldelta_u_tmp!=ldelta_u_capi) {
    Py_XDECREF(capi_ldelta_u_tmp); }
  }  /*if (capi_ldelta_u_tmp == NULL) ... else of ldelta_u*/
  /* End of cleaning variable ldelta_u */
  if((PyObject *)capi_ldelta_v_tmp!=ldelta_v_capi) {
    Py_XDECREF(capi_ldelta_v_tmp); }
  }  /*if (capi_ldelta_v_tmp == NULL) ... else of ldelta_v*/
  /* End of cleaning variable ldelta_v */
  if((PyObject *)capi_p_tmp!=p_capi) {
    Py_XDECREF(capi_p_tmp); }
  }  /*if (capi_p_tmp == NULL) ... else of p*/
  /* End of cleaning variable p */
  }  /*if (capi_q_r_tmp == NULL) ... else of q_r*/
  /* End of cleaning variable q_r */
  }  /*if (capi_q_l_tmp == NULL) ... else of q_l*/
  /* End of cleaning variable q_l */
  } /*if (f2py_success) of qy*/
  /* End of cleaning variable qy */
  } /*if (f2py_success) of nvar*/
  /* End of cleaning variable nvar */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  } /*if (f2py_success) of qx*/
  /* End of cleaning variable qx */
  } /*if (f2py_success) of dx*/
  /* End of cleaning variable dx */
  } /*if (f2py_success) of ng*/
  /* End of cleaning variable ng */
  } /*if (f2py_success) of idir*/
  /* End of cleaning variable idir */
    CFUNCSMESS("Restoring jmpbuf for `speed`.\n");
    cb_speed_in_states__user__routines_capi = speed_capi;
    Py_DECREF(cb_speed_in_states__user__routines_args_capi);
    cb_speed_in_states__user__routines_args_capi = speed_args_capi;
    cb_speed_in_states__user__routines_nofargs = speed_nofargs_capi;
    memcpy(&cb_speed_in_states__user__routines_jmpbuf,&speed_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable speed */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of states *******************************/

/******************************** riemann_cgf ********************************/
static char doc_f2py_rout_interface_f_riemann_cgf[] = "\
F = riemann_cgf(idir,qx,qy,ng,nvar,idens,ixmom,iymom,iener,lower_solid,upper_solid,real_gamma,pres,U_l,U_r,[real_gamma_extra_args,pres_extra_args])\n\nWrapper for ``riemann_cgf``.\
\n\nParameters\n----------\n"
"idir : input int\n"
"qx : input int\n"
"qy : input int\n"
"ng : input int\n"
"nvar : input int\n"
"idens : input int\n"
"ixmom : input int\n"
"iymom : input int\n"
"iener : input int\n"
"lower_solid : input int\n"
"upper_solid : input int\n"
"real_gamma : call-back function\n"
"pres : call-back function\n"
"U_l : input rank-3 array('d') with bounds (qx,qy,nvar)\n"
"U_r : input rank-3 array('d') with bounds (qx,qy,nvar)\n"
"\nOther Parameters\n----------------\n"
"real_gamma_extra_args : input tuple, optional\n    Default: ()\n"
"pres_extra_args : input tuple, optional\n    Default: ()\n"
"\nReturns\n-------\n"
"F : rank-3 array('d') with bounds (qx,qy,nvar)\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"  def real_gamma(temp): return temp1\n\
  Required arguments:\n"
"    temp : input rank-1 array('d') with bounds (2)\n"
"  Return objects:\n"
"    temp1 : float\n"
"  def pres(temp): return temp1\n\
  Required arguments:\n"
"    temp : input rank-1 array('d') with bounds (2)\n"
"  Return objects:\n"
"    temp1 : float";
/* extern void F_FUNC_US(riemann_cgf,RIEMANN_CGF)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,cb_real_gamma_in_riemann_cgf__user__routines_typedef,cb_pres_in_riemann_cgf__user__routines_typedef,double*,double*,double*); */
static PyObject *f2py_rout_interface_f_riemann_cgf(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,cb_real_gamma_in_riemann_cgf__user__routines_typedef,cb_pres_in_riemann_cgf__user__routines_typedef,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int idir = 0;
  PyObject *idir_capi = Py_None;
  int qx = 0;
  PyObject *qx_capi = Py_None;
  int qy = 0;
  PyObject *qy_capi = Py_None;
  int ng = 0;
  PyObject *ng_capi = Py_None;
  int nvar = 0;
  PyObject *nvar_capi = Py_None;
  int idens = 0;
  PyObject *idens_capi = Py_None;
  int ixmom = 0;
  PyObject *ixmom_capi = Py_None;
  int iymom = 0;
  PyObject *iymom_capi = Py_None;
  int iener = 0;
  PyObject *iener_capi = Py_None;
  int lower_solid = 0;
  PyObject *lower_solid_capi = Py_None;
  int upper_solid = 0;
  PyObject *upper_solid_capi = Py_None;
  PyObject *real_gamma_capi = Py_None;
  PyTupleObject *real_gamma_xa_capi = NULL;
  PyTupleObject *real_gamma_args_capi = NULL;
  int real_gamma_nofargs_capi = 0;
  cb_real_gamma_in_riemann_cgf__user__routines_typedef real_gamma_cptr;
  PyObject *pres_capi = Py_None;
  PyTupleObject *pres_xa_capi = NULL;
  PyTupleObject *pres_args_capi = NULL;
  int pres_nofargs_capi = 0;
  cb_pres_in_riemann_cgf__user__routines_typedef pres_cptr;
  double *U_l = NULL;
  npy_intp U_l_Dims[3] = {-1, -1, -1};
  const int U_l_Rank = 3;
  PyArrayObject *capi_U_l_tmp = NULL;
  int capi_U_l_intent = 0;
  PyObject *U_l_capi = Py_None;
  double *U_r = NULL;
  npy_intp U_r_Dims[3] = {-1, -1, -1};
  const int U_r_Rank = 3;
  PyArrayObject *capi_U_r_tmp = NULL;
  int capi_U_r_intent = 0;
  PyObject *U_r_capi = Py_None;
  double *F = NULL;
  npy_intp F_Dims[3] = {-1, -1, -1};
  const int F_Rank = 3;
  PyArrayObject *capi_F_tmp = NULL;
  int capi_F_intent = 0;
  static char *capi_kwlist[] = {"idir","qx","qy","ng","nvar","idens","ixmom","iymom","iener","lower_solid","upper_solid","real_gamma","pres","U_l","U_r","real_gamma_extra_args","pres_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOO|O!O!:interface_f.riemann_cgf",\
    capi_kwlist,&idir_capi,&qx_capi,&qy_capi,&ng_capi,&nvar_capi,&idens_capi,&ixmom_capi,&iymom_capi,&iener_capi,&lower_solid_capi,&upper_solid_capi,&real_gamma_capi,&pres_capi,&U_l_capi,&U_r_capi,&PyTuple_Type,&real_gamma_xa_capi,&PyTuple_Type,&pres_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable real_gamma */
if(F2PyCapsule_Check(real_gamma_capi)) {
  real_gamma_cptr = F2PyCapsule_AsVoidPtr(real_gamma_capi);
} else {
  real_gamma_cptr = cb_real_gamma_in_riemann_cgf__user__routines;
}

  real_gamma_nofargs_capi = cb_real_gamma_in_riemann_cgf__user__routines_nofargs;
  if (create_cb_arglist(real_gamma_capi,real_gamma_xa_capi,1,0,&cb_real_gamma_in_riemann_cgf__user__routines_nofargs,&real_gamma_args_capi,"failed in processing argument list for call-back real_gamma.")) {
    jmp_buf real_gamma_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `real_gamma`.\n");
    SWAP(real_gamma_capi,cb_real_gamma_in_riemann_cgf__user__routines_capi,PyObject);
    SWAP(real_gamma_args_capi,cb_real_gamma_in_riemann_cgf__user__routines_args_capi,PyTupleObject);
    memcpy(&real_gamma_jmpbuf,&cb_real_gamma_in_riemann_cgf__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable lower_solid */
    f2py_success = int_from_pyobj(&lower_solid,lower_solid_capi,"interface_f.riemann_cgf() 10th argument (lower_solid) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pres */
if(F2PyCapsule_Check(pres_capi)) {
  pres_cptr = F2PyCapsule_AsVoidPtr(pres_capi);
} else {
  pres_cptr = cb_pres_in_riemann_cgf__user__routines;
}

  pres_nofargs_capi = cb_pres_in_riemann_cgf__user__routines_nofargs;
  if (create_cb_arglist(pres_capi,pres_xa_capi,1,0,&cb_pres_in_riemann_cgf__user__routines_nofargs,&pres_args_capi,"failed in processing argument list for call-back pres.")) {
    jmp_buf pres_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `pres`.\n");
    SWAP(pres_capi,cb_pres_in_riemann_cgf__user__routines_capi,PyObject);
    SWAP(pres_args_capi,cb_pres_in_riemann_cgf__user__routines_args_capi,PyTupleObject);
    memcpy(&pres_jmpbuf,&cb_pres_in_riemann_cgf__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable nvar */
    f2py_success = int_from_pyobj(&nvar,nvar_capi,"interface_f.riemann_cgf() 5th argument (nvar) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iener */
    f2py_success = int_from_pyobj(&iener,iener_capi,"interface_f.riemann_cgf() 9th argument (iener) can't be converted to int");
  if (f2py_success) {
  /* Processing variable qy */
    f2py_success = int_from_pyobj(&qy,qy_capi,"interface_f.riemann_cgf() 3rd argument (qy) can't be converted to int");
  if (f2py_success) {
  /* Processing variable qx */
    f2py_success = int_from_pyobj(&qx,qx_capi,"interface_f.riemann_cgf() 2nd argument (qx) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ixmom */
    f2py_success = int_from_pyobj(&ixmom,ixmom_capi,"interface_f.riemann_cgf() 7th argument (ixmom) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iymom */
    f2py_success = int_from_pyobj(&iymom,iymom_capi,"interface_f.riemann_cgf() 8th argument (iymom) can't be converted to int");
  if (f2py_success) {
  /* Processing variable idir */
    f2py_success = int_from_pyobj(&idir,idir_capi,"interface_f.riemann_cgf() 1st argument (idir) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ng */
    f2py_success = int_from_pyobj(&ng,ng_capi,"interface_f.riemann_cgf() 4th argument (ng) can't be converted to int");
  if (f2py_success) {
  /* Processing variable upper_solid */
    f2py_success = int_from_pyobj(&upper_solid,upper_solid_capi,"interface_f.riemann_cgf() 11st argument (upper_solid) can't be converted to int");
  if (f2py_success) {
  /* Processing variable idens */
    f2py_success = int_from_pyobj(&idens,idens_capi,"interface_f.riemann_cgf() 6th argument (idens) can't be converted to int");
  if (f2py_success) {
  /* Processing variable F */
  F_Dims[0]=qx,F_Dims[1]=qy,F_Dims[2]=nvar;
  capi_F_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_F_tmp = array_from_pyobj(NPY_DOUBLE,F_Dims,F_Rank,capi_F_intent,Py_None);
  if (capi_F_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting hidden `F' of interface_f.riemann_cgf to C/Fortran array" );
  } else {
    F = (double *)(PyArray_DATA(capi_F_tmp));

  /* Processing variable U_l */
  U_l_Dims[0]=qx,U_l_Dims[1]=qy,U_l_Dims[2]=nvar;
  capi_U_l_intent |= F2PY_INTENT_IN;
  capi_U_l_tmp = array_from_pyobj(NPY_DOUBLE,U_l_Dims,U_l_Rank,capi_U_l_intent,U_l_capi);
  if (capi_U_l_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 14th argument `U_l' of interface_f.riemann_cgf to C/Fortran array" );
  } else {
    U_l = (double *)(PyArray_DATA(capi_U_l_tmp));

  /* Processing variable U_r */
  U_r_Dims[0]=qx,U_r_Dims[1]=qy,U_r_Dims[2]=nvar;
  capi_U_r_intent |= F2PY_INTENT_IN;
  capi_U_r_tmp = array_from_pyobj(NPY_DOUBLE,U_r_Dims,U_r_Rank,capi_U_r_intent,U_r_capi);
  if (capi_U_r_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 15th argument `U_r' of interface_f.riemann_cgf to C/Fortran array" );
  } else {
    U_r = (double *)(PyArray_DATA(capi_U_r_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_real_gamma_in_riemann_cgf__user__routines_jmpbuf)) || (setjmp(cb_pres_in_riemann_cgf__user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(&idir,&qx,&qy,&ng,&nvar,&idens,&ixmom,&iymom,&iener,&lower_solid,&upper_solid,real_gamma_cptr,pres_cptr,U_l,U_r,F);
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_F_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_U_r_tmp!=U_r_capi) {
    Py_XDECREF(capi_U_r_tmp); }
  }  /*if (capi_U_r_tmp == NULL) ... else of U_r*/
  /* End of cleaning variable U_r */
  if((PyObject *)capi_U_l_tmp!=U_l_capi) {
    Py_XDECREF(capi_U_l_tmp); }
  }  /*if (capi_U_l_tmp == NULL) ... else of U_l*/
  /* End of cleaning variable U_l */
  }  /*if (capi_F_tmp == NULL) ... else of F*/
  /* End of cleaning variable F */
  } /*if (f2py_success) of idens*/
  /* End of cleaning variable idens */
  } /*if (f2py_success) of upper_solid*/
  /* End of cleaning variable upper_solid */
  } /*if (f2py_success) of ng*/
  /* End of cleaning variable ng */
  } /*if (f2py_success) of idir*/
  /* End of cleaning variable idir */
  } /*if (f2py_success) of iymom*/
  /* End of cleaning variable iymom */
  } /*if (f2py_success) of ixmom*/
  /* End of cleaning variable ixmom */
  } /*if (f2py_success) of qx*/
  /* End of cleaning variable qx */
  } /*if (f2py_success) of qy*/
  /* End of cleaning variable qy */
  } /*if (f2py_success) of iener*/
  /* End of cleaning variable iener */
  } /*if (f2py_success) of nvar*/
  /* End of cleaning variable nvar */
    CFUNCSMESS("Restoring jmpbuf for `pres`.\n");
    cb_pres_in_riemann_cgf__user__routines_capi = pres_capi;
    Py_DECREF(cb_pres_in_riemann_cgf__user__routines_args_capi);
    cb_pres_in_riemann_cgf__user__routines_args_capi = pres_args_capi;
    cb_pres_in_riemann_cgf__user__routines_nofargs = pres_nofargs_capi;
    memcpy(&cb_pres_in_riemann_cgf__user__routines_jmpbuf,&pres_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable pres */
  } /*if (f2py_success) of lower_solid*/
  /* End of cleaning variable lower_solid */
    CFUNCSMESS("Restoring jmpbuf for `real_gamma`.\n");
    cb_real_gamma_in_riemann_cgf__user__routines_capi = real_gamma_capi;
    Py_DECREF(cb_real_gamma_in_riemann_cgf__user__routines_args_capi);
    cb_real_gamma_in_riemann_cgf__user__routines_args_capi = real_gamma_args_capi;
    cb_real_gamma_in_riemann_cgf__user__routines_nofargs = real_gamma_nofargs_capi;
    memcpy(&cb_real_gamma_in_riemann_cgf__user__routines_jmpbuf,&real_gamma_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable real_gamma */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of riemann_cgf *****************************/

/******************************** riemann_HLLC ********************************/
static char doc_f2py_rout_interface_f_riemann_HLLC[] = "\
F = riemann_HLLC(idir,qx,qy,ng,nvar,idens,ixmom,iymom,iener,lower_solid,upper_solid,gamma,U_l,U_r)\n\nWrapper for ``riemann_HLLC``.\
\n\nParameters\n----------\n"
"idir : input int\n"
"qx : input int\n"
"qy : input int\n"
"ng : input int\n"
"nvar : input int\n"
"idens : input int\n"
"ixmom : input int\n"
"iymom : input int\n"
"iener : input int\n"
"lower_solid : input int\n"
"upper_solid : input int\n"
"gamma : input float\n"
"U_l : input rank-3 array('d') with bounds (qx,qy,nvar)\n"
"U_r : input rank-3 array('d') with bounds (qx,qy,nvar)\n"
"\nReturns\n-------\n"
"F : rank-3 array('d') with bounds (qx,qy,nvar)";
/* extern void F_FUNC_US(riemann_HLLC,RIEMANN_HLLC)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*); */
static PyObject *f2py_rout_interface_f_riemann_HLLC(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int idir = 0;
  PyObject *idir_capi = Py_None;
  int qx = 0;
  PyObject *qx_capi = Py_None;
  int qy = 0;
  PyObject *qy_capi = Py_None;
  int ng = 0;
  PyObject *ng_capi = Py_None;
  int nvar = 0;
  PyObject *nvar_capi = Py_None;
  int idens = 0;
  PyObject *idens_capi = Py_None;
  int ixmom = 0;
  PyObject *ixmom_capi = Py_None;
  int iymom = 0;
  PyObject *iymom_capi = Py_None;
  int iener = 0;
  PyObject *iener_capi = Py_None;
  int lower_solid = 0;
  PyObject *lower_solid_capi = Py_None;
  int upper_solid = 0;
  PyObject *upper_solid_capi = Py_None;
  double gamma = 0;
  PyObject *gamma_capi = Py_None;
  double *U_l = NULL;
  npy_intp U_l_Dims[3] = {-1, -1, -1};
  const int U_l_Rank = 3;
  PyArrayObject *capi_U_l_tmp = NULL;
  int capi_U_l_intent = 0;
  PyObject *U_l_capi = Py_None;
  double *U_r = NULL;
  npy_intp U_r_Dims[3] = {-1, -1, -1};
  const int U_r_Rank = 3;
  PyArrayObject *capi_U_r_tmp = NULL;
  int capi_U_r_intent = 0;
  PyObject *U_r_capi = Py_None;
  double *F = NULL;
  npy_intp F_Dims[3] = {-1, -1, -1};
  const int F_Rank = 3;
  PyArrayObject *capi_F_tmp = NULL;
  int capi_F_intent = 0;
  static char *capi_kwlist[] = {"idir","qx","qy","ng","nvar","idens","ixmom","iymom","iener","lower_solid","upper_solid","gamma","U_l","U_r",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOO:interface_f.riemann_HLLC",\
    capi_kwlist,&idir_capi,&qx_capi,&qy_capi,&ng_capi,&nvar_capi,&idens_capi,&ixmom_capi,&iymom_capi,&iener_capi,&lower_solid_capi,&upper_solid_capi,&gamma_capi,&U_l_capi,&U_r_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable qy */
    f2py_success = int_from_pyobj(&qy,qy_capi,"interface_f.riemann_HLLC() 3rd argument (qy) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ixmom */
    f2py_success = int_from_pyobj(&ixmom,ixmom_capi,"interface_f.riemann_HLLC() 7th argument (ixmom) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iymom */
    f2py_success = int_from_pyobj(&iymom,iymom_capi,"interface_f.riemann_HLLC() 8th argument (iymom) can't be converted to int");
  if (f2py_success) {
  /* Processing variable idir */
    f2py_success = int_from_pyobj(&idir,idir_capi,"interface_f.riemann_HLLC() 1st argument (idir) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ng */
    f2py_success = int_from_pyobj(&ng,ng_capi,"interface_f.riemann_HLLC() 4th argument (ng) can't be converted to int");
  if (f2py_success) {
  /* Processing variable lower_solid */
    f2py_success = int_from_pyobj(&lower_solid,lower_solid_capi,"interface_f.riemann_HLLC() 10th argument (lower_solid) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nvar */
    f2py_success = int_from_pyobj(&nvar,nvar_capi,"interface_f.riemann_HLLC() 5th argument (nvar) can't be converted to int");
  if (f2py_success) {
  /* Processing variable qx */
    f2py_success = int_from_pyobj(&qx,qx_capi,"interface_f.riemann_HLLC() 2nd argument (qx) can't be converted to int");
  if (f2py_success) {
  /* Processing variable upper_solid */
    f2py_success = int_from_pyobj(&upper_solid,upper_solid_capi,"interface_f.riemann_HLLC() 11st argument (upper_solid) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iener */
    f2py_success = int_from_pyobj(&iener,iener_capi,"interface_f.riemann_HLLC() 9th argument (iener) can't be converted to int");
  if (f2py_success) {
  /* Processing variable idens */
    f2py_success = int_from_pyobj(&idens,idens_capi,"interface_f.riemann_HLLC() 6th argument (idens) can't be converted to int");
  if (f2py_success) {
  /* Processing variable gamma */
    f2py_success = double_from_pyobj(&gamma,gamma_capi,"interface_f.riemann_HLLC() 12nd argument (gamma) can't be converted to double");
  if (f2py_success) {
  /* Processing variable F */
  F_Dims[0]=qx,F_Dims[1]=qy,F_Dims[2]=nvar;
  capi_F_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_F_tmp = array_from_pyobj(NPY_DOUBLE,F_Dims,F_Rank,capi_F_intent,Py_None);
  if (capi_F_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting hidden `F' of interface_f.riemann_HLLC to C/Fortran array" );
  } else {
    F = (double *)(PyArray_DATA(capi_F_tmp));

  /* Processing variable U_l */
  U_l_Dims[0]=qx,U_l_Dims[1]=qy,U_l_Dims[2]=nvar;
  capi_U_l_intent |= F2PY_INTENT_IN;
  capi_U_l_tmp = array_from_pyobj(NPY_DOUBLE,U_l_Dims,U_l_Rank,capi_U_l_intent,U_l_capi);
  if (capi_U_l_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 13rd argument `U_l' of interface_f.riemann_HLLC to C/Fortran array" );
  } else {
    U_l = (double *)(PyArray_DATA(capi_U_l_tmp));

  /* Processing variable U_r */
  U_r_Dims[0]=qx,U_r_Dims[1]=qy,U_r_Dims[2]=nvar;
  capi_U_r_intent |= F2PY_INTENT_IN;
  capi_U_r_tmp = array_from_pyobj(NPY_DOUBLE,U_r_Dims,U_r_Rank,capi_U_r_intent,U_r_capi);
  if (capi_U_r_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 14th argument `U_r' of interface_f.riemann_HLLC to C/Fortran array" );
  } else {
    U_r = (double *)(PyArray_DATA(capi_U_r_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&idir,&qx,&qy,&ng,&nvar,&idens,&ixmom,&iymom,&iener,&lower_solid,&upper_solid,&gamma,U_l,U_r,F);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_F_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_U_r_tmp!=U_r_capi) {
    Py_XDECREF(capi_U_r_tmp); }
  }  /*if (capi_U_r_tmp == NULL) ... else of U_r*/
  /* End of cleaning variable U_r */
  if((PyObject *)capi_U_l_tmp!=U_l_capi) {
    Py_XDECREF(capi_U_l_tmp); }
  }  /*if (capi_U_l_tmp == NULL) ... else of U_l*/
  /* End of cleaning variable U_l */
  }  /*if (capi_F_tmp == NULL) ... else of F*/
  /* End of cleaning variable F */
  } /*if (f2py_success) of gamma*/
  /* End of cleaning variable gamma */
  } /*if (f2py_success) of idens*/
  /* End of cleaning variable idens */
  } /*if (f2py_success) of iener*/
  /* End of cleaning variable iener */
  } /*if (f2py_success) of upper_solid*/
  /* End of cleaning variable upper_solid */
  } /*if (f2py_success) of qx*/
  /* End of cleaning variable qx */
  } /*if (f2py_success) of nvar*/
  /* End of cleaning variable nvar */
  } /*if (f2py_success) of lower_solid*/
  /* End of cleaning variable lower_solid */
  } /*if (f2py_success) of ng*/
  /* End of cleaning variable ng */
  } /*if (f2py_success) of idir*/
  /* End of cleaning variable idir */
  } /*if (f2py_success) of iymom*/
  /* End of cleaning variable iymom */
  } /*if (f2py_success) of ixmom*/
  /* End of cleaning variable ixmom */
  } /*if (f2py_success) of qy*/
  /* End of cleaning variable qy */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of riemann_HLLC ****************************/

/********************************** consFlux **********************************/
static char doc_f2py_rout_interface_f_consFlux[] = "\
F = consFlux(idir,gamma,idens,ixmom,iymom,iener,U_state,[nvar])\n\nWrapper for ``consFlux``.\
\n\nParameters\n----------\n"
"idir : input int\n"
"gamma : input float\n"
"idens : input int\n"
"ixmom : input int\n"
"iymom : input int\n"
"iener : input int\n"
"U_state : input rank-1 array('d') with bounds (nvar)\n"
"\nOther Parameters\n----------------\n"
"nvar : input int, optional\n    Default: len(U_state)\n"
"\nReturns\n-------\n"
"F : rank-1 array('d') with bounds (nvar)";
/* extern void F_FUNC(consFlux,CONSFLUX)(int*,double*,int*,int*,int*,int*,int*,double*,double*); */
static PyObject *f2py_rout_interface_f_consFlux(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,int*,int*,int*,int*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int idir = 0;
  PyObject *idir_capi = Py_None;
  double gamma = 0;
  PyObject *gamma_capi = Py_None;
  int idens = 0;
  PyObject *idens_capi = Py_None;
  int ixmom = 0;
  PyObject *ixmom_capi = Py_None;
  int iymom = 0;
  PyObject *iymom_capi = Py_None;
  int iener = 0;
  PyObject *iener_capi = Py_None;
  int nvar = 0;
  PyObject *nvar_capi = Py_None;
  double *U_state = NULL;
  npy_intp U_state_Dims[1] = {-1};
  const int U_state_Rank = 1;
  PyArrayObject *capi_U_state_tmp = NULL;
  int capi_U_state_intent = 0;
  PyObject *U_state_capi = Py_None;
  double *F = NULL;
  npy_intp F_Dims[1] = {-1};
  const int F_Rank = 1;
  PyArrayObject *capi_F_tmp = NULL;
  int capi_F_intent = 0;
  static char *capi_kwlist[] = {"idir","gamma","idens","ixmom","iymom","iener","U_state","nvar",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|O:interface_f.consFlux",\
    capi_kwlist,&idir_capi,&gamma_capi,&idens_capi,&ixmom_capi,&iymom_capi,&iener_capi,&U_state_capi,&nvar_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ixmom */
    f2py_success = int_from_pyobj(&ixmom,ixmom_capi,"interface_f.consFlux() 4th argument (ixmom) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iymom */
    f2py_success = int_from_pyobj(&iymom,iymom_capi,"interface_f.consFlux() 5th argument (iymom) can't be converted to int");
  if (f2py_success) {
  /* Processing variable idens */
    f2py_success = int_from_pyobj(&idens,idens_capi,"interface_f.consFlux() 3rd argument (idens) can't be converted to int");
  if (f2py_success) {
  /* Processing variable idir */
    f2py_success = int_from_pyobj(&idir,idir_capi,"interface_f.consFlux() 1st argument (idir) can't be converted to int");
  if (f2py_success) {
  /* Processing variable U_state */
  ;
  capi_U_state_intent |= F2PY_INTENT_IN;
  capi_U_state_tmp = array_from_pyobj(NPY_DOUBLE,U_state_Dims,U_state_Rank,capi_U_state_intent,U_state_capi);
  if (capi_U_state_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 7th argument `U_state' of interface_f.consFlux to C/Fortran array" );
  } else {
    U_state = (double *)(PyArray_DATA(capi_U_state_tmp));

  /* Processing variable iener */
    f2py_success = int_from_pyobj(&iener,iener_capi,"interface_f.consFlux() 6th argument (iener) can't be converted to int");
  if (f2py_success) {
  /* Processing variable gamma */
    f2py_success = double_from_pyobj(&gamma,gamma_capi,"interface_f.consFlux() 2nd argument (gamma) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nvar */
  if (nvar_capi == Py_None) nvar = len(U_state); else
    f2py_success = int_from_pyobj(&nvar,nvar_capi,"interface_f.consFlux() 1st keyword (nvar) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(U_state)>=nvar,"len(U_state)>=nvar","1st keyword nvar","consFlux:nvar=%d",nvar) {
  /* Processing variable F */
  F_Dims[0]=nvar;
  capi_F_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_F_tmp = array_from_pyobj(NPY_DOUBLE,F_Dims,F_Rank,capi_F_intent,Py_None);
  if (capi_F_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting hidden `F' of interface_f.consFlux to C/Fortran array" );
  } else {
    F = (double *)(PyArray_DATA(capi_F_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&idir,&gamma,&idens,&ixmom,&iymom,&iener,&nvar,U_state,F);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_F_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_F_tmp == NULL) ... else of F*/
  /* End of cleaning variable F */
  } /*CHECKSCALAR(len(U_state)>=nvar)*/
  } /*if (f2py_success) of nvar*/
  /* End of cleaning variable nvar */
  } /*if (f2py_success) of gamma*/
  /* End of cleaning variable gamma */
  } /*if (f2py_success) of iener*/
  /* End of cleaning variable iener */
  if((PyObject *)capi_U_state_tmp!=U_state_capi) {
    Py_XDECREF(capi_U_state_tmp); }
  }  /*if (capi_U_state_tmp == NULL) ... else of U_state*/
  /* End of cleaning variable U_state */
  } /*if (f2py_success) of idir*/
  /* End of cleaning variable idir */
  } /*if (f2py_success) of idens*/
  /* End of cleaning variable idens */
  } /*if (f2py_success) of iymom*/
  /* End of cleaning variable iymom */
  } /*if (f2py_success) of ixmom*/
  /* End of cleaning variable ixmom */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of consFlux ******************************/

/**************************** artificial_viscosity ****************************/
static char doc_f2py_rout_interface_f_artificial_viscosity[] = "\
avisco_x,avisco_y = artificial_viscosity(qx,qy,ng,dx,dy,cvisc,u,v)\n\nWrapper for ``artificial_viscosity``.\
\n\nParameters\n----------\n"
"qx : input int\n"
"qy : input int\n"
"ng : input int\n"
"dx : input float\n"
"dy : input float\n"
"cvisc : input float\n"
"u : input rank-2 array('d') with bounds (qx,qy)\n"
"v : input rank-2 array('d') with bounds (qx,qy)\n"
"\nReturns\n-------\n"
"avisco_x : rank-2 array('d') with bounds (qx,qy)\n"
"avisco_y : rank-2 array('d') with bounds (qx,qy)";
/* extern void F_FUNC_US(artificial_viscosity,ARTIFICIAL_VISCOSITY)(int*,int*,int*,double*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_interface_f_artificial_viscosity(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,double*,double*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int qx = 0;
  PyObject *qx_capi = Py_None;
  int qy = 0;
  PyObject *qy_capi = Py_None;
  int ng = 0;
  PyObject *ng_capi = Py_None;
  double dx = 0;
  PyObject *dx_capi = Py_None;
  double dy = 0;
  PyObject *dy_capi = Py_None;
  double cvisc = 0;
  PyObject *cvisc_capi = Py_None;
  double *u = NULL;
  npy_intp u_Dims[2] = {-1, -1};
  const int u_Rank = 2;
  PyArrayObject *capi_u_tmp = NULL;
  int capi_u_intent = 0;
  PyObject *u_capi = Py_None;
  double *v = NULL;
  npy_intp v_Dims[2] = {-1, -1};
  const int v_Rank = 2;
  PyArrayObject *capi_v_tmp = NULL;
  int capi_v_intent = 0;
  PyObject *v_capi = Py_None;
  double *avisco_x = NULL;
  npy_intp avisco_x_Dims[2] = {-1, -1};
  const int avisco_x_Rank = 2;
  PyArrayObject *capi_avisco_x_tmp = NULL;
  int capi_avisco_x_intent = 0;
  double *avisco_y = NULL;
  npy_intp avisco_y_Dims[2] = {-1, -1};
  const int avisco_y_Rank = 2;
  PyArrayObject *capi_avisco_y_tmp = NULL;
  int capi_avisco_y_intent = 0;
  static char *capi_kwlist[] = {"qx","qy","ng","dx","dy","cvisc","u","v",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO:interface_f.artificial_viscosity",\
    capi_kwlist,&qx_capi,&qy_capi,&ng_capi,&dx_capi,&dy_capi,&cvisc_capi,&u_capi,&v_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable dx */
    f2py_success = double_from_pyobj(&dx,dx_capi,"interface_f.artificial_viscosity() 4th argument (dx) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dy */
    f2py_success = double_from_pyobj(&dy,dy_capi,"interface_f.artificial_viscosity() 5th argument (dy) can't be converted to double");
  if (f2py_success) {
  /* Processing variable qy */
    f2py_success = int_from_pyobj(&qy,qy_capi,"interface_f.artificial_viscosity() 2nd argument (qy) can't be converted to int");
  if (f2py_success) {
  /* Processing variable qx */
    f2py_success = int_from_pyobj(&qx,qx_capi,"interface_f.artificial_viscosity() 1st argument (qx) can't be converted to int");
  if (f2py_success) {
  /* Processing variable cvisc */
    f2py_success = double_from_pyobj(&cvisc,cvisc_capi,"interface_f.artificial_viscosity() 6th argument (cvisc) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ng */
    f2py_success = int_from_pyobj(&ng,ng_capi,"interface_f.artificial_viscosity() 3rd argument (ng) can't be converted to int");
  if (f2py_success) {
  /* Processing variable avisco_y */
  avisco_y_Dims[0]=qx,avisco_y_Dims[1]=qy;
  capi_avisco_y_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_avisco_y_tmp = array_from_pyobj(NPY_DOUBLE,avisco_y_Dims,avisco_y_Rank,capi_avisco_y_intent,Py_None);
  if (capi_avisco_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting hidden `avisco_y' of interface_f.artificial_viscosity to C/Fortran array" );
  } else {
    avisco_y = (double *)(PyArray_DATA(capi_avisco_y_tmp));

  /* Processing variable avisco_x */
  avisco_x_Dims[0]=qx,avisco_x_Dims[1]=qy;
  capi_avisco_x_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_avisco_x_tmp = array_from_pyobj(NPY_DOUBLE,avisco_x_Dims,avisco_x_Rank,capi_avisco_x_intent,Py_None);
  if (capi_avisco_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting hidden `avisco_x' of interface_f.artificial_viscosity to C/Fortran array" );
  } else {
    avisco_x = (double *)(PyArray_DATA(capi_avisco_x_tmp));

  /* Processing variable u */
  u_Dims[0]=qx,u_Dims[1]=qy;
  capi_u_intent |= F2PY_INTENT_IN;
  capi_u_tmp = array_from_pyobj(NPY_DOUBLE,u_Dims,u_Rank,capi_u_intent,u_capi);
  if (capi_u_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 7th argument `u' of interface_f.artificial_viscosity to C/Fortran array" );
  } else {
    u = (double *)(PyArray_DATA(capi_u_tmp));

  /* Processing variable v */
  v_Dims[0]=qx,v_Dims[1]=qy;
  capi_v_intent |= F2PY_INTENT_IN;
  capi_v_tmp = array_from_pyobj(NPY_DOUBLE,v_Dims,v_Rank,capi_v_intent,v_capi);
  if (capi_v_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(interface_f_error,"failed in converting 8th argument `v' of interface_f.artificial_viscosity to C/Fortran array" );
  } else {
    v = (double *)(PyArray_DATA(capi_v_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&qx,&qy,&ng,&dx,&dy,&cvisc,u,v,avisco_x,avisco_y);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_avisco_x_tmp,capi_avisco_y_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_v_tmp!=v_capi) {
    Py_XDECREF(capi_v_tmp); }
  }  /*if (capi_v_tmp == NULL) ... else of v*/
  /* End of cleaning variable v */
  if((PyObject *)capi_u_tmp!=u_capi) {
    Py_XDECREF(capi_u_tmp); }
  }  /*if (capi_u_tmp == NULL) ... else of u*/
  /* End of cleaning variable u */
  }  /*if (capi_avisco_x_tmp == NULL) ... else of avisco_x*/
  /* End of cleaning variable avisco_x */
  }  /*if (capi_avisco_y_tmp == NULL) ... else of avisco_y*/
  /* End of cleaning variable avisco_y */
  } /*if (f2py_success) of ng*/
  /* End of cleaning variable ng */
  } /*if (f2py_success) of cvisc*/
  /* End of cleaning variable cvisc */
  } /*if (f2py_success) of qx*/
  /* End of cleaning variable qx */
  } /*if (f2py_success) of qy*/
  /* End of cleaning variable qy */
  } /*if (f2py_success) of dy*/
  /* End of cleaning variable dy */
  } /*if (f2py_success) of dx*/
  /* End of cleaning variable dx */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of artificial_viscosity ************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"states",-1,{{-1}},0,(char *)F_FUNC(states,STATES),(f2py_init_func)f2py_rout_interface_f_states,doc_f2py_rout_interface_f_states},
  {"riemann_cgf",-1,{{-1}},0,(char *)F_FUNC_US(riemann_cgf,RIEMANN_CGF),(f2py_init_func)f2py_rout_interface_f_riemann_cgf,doc_f2py_rout_interface_f_riemann_cgf},
  {"riemann_HLLC",-1,{{-1}},0,(char *)F_FUNC_US(riemann_HLLC,RIEMANN_HLLC),(f2py_init_func)f2py_rout_interface_f_riemann_HLLC,doc_f2py_rout_interface_f_riemann_HLLC},
  {"consFlux",-1,{{-1}},0,(char *)F_FUNC(consFlux,CONSFLUX),(f2py_init_func)f2py_rout_interface_f_consFlux,doc_f2py_rout_interface_f_consFlux},
  {"artificial_viscosity",-1,{{-1}},0,(char *)F_FUNC_US(artificial_viscosity,ARTIFICIAL_VISCOSITY),(f2py_init_func)f2py_rout_interface_f_artificial_viscosity,doc_f2py_rout_interface_f_artificial_viscosity},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "interface_f",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_interface_f(void) {
#else
#define RETVAL
PyMODINIT_FUNC initinterface_f(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = interface_f_module = PyModule_Create(&moduledef);
#else
  m = interface_f_module = Py_InitModule("interface_f", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module interface_f (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'interface_f' is auto-generated with f2py (version:2).\nFunctions:\n"
"  q_l,q_r = states(idir,qx,qy,ng,dx,dt,nvar,speed,r,u,v,p,ldelta_r,ldelta_u,ldelta_v,ldelta_p,speed_extra_args=())\n"
"  F = riemann_cgf(idir,qx,qy,ng,nvar,idens,ixmom,iymom,iener,lower_solid,upper_solid,real_gamma,pres,U_l,U_r,real_gamma_extra_args=(),pres_extra_args=())\n"
"  F = riemann_HLLC(idir,qx,qy,ng,nvar,idens,ixmom,iymom,iener,lower_solid,upper_solid,gamma,U_l,U_r)\n"
"  F = consFlux(idir,gamma,idens,ixmom,iymom,iener,U_state,nvar=len(U_state))\n"
"  avisco_x,avisco_y = artificial_viscosity(qx,qy,ng,dx,dy,cvisc,u,v)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  interface_f_error = PyErr_NewException ("interface_f.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));





/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"interface_f");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
